# theme: solitude-float
background              #101315
foreground              #CACCCC
cursor                  #CACCCC
cursor_text_color       #101315
selection_foreground    #CACCCC
selection_background    #343D41
active_tab_background   #1A1E20
active_tab_foreground   #798186
inactive_tab_background #202528
inactive_tab_foreground #798186

background_opacity 0.90
