background = 0xFF101315
base = 0xFF1A1E20
text = 0xFFCACCCC
alternate_base = 0xFF202528
bright_text = 0xFF798186
accent = 0xFF798186
link_text = 0xFF798186
accent_secondary = 0xFFA5AEB4
font_family = "IBM Plex Mono"
font_family_monospace = "monospace"
font_size = 13
small_font_size = 10
rounding_large = 0
rounding_small = 0
