# theme: solitude
background              #101315
foreground              #CACCCC
cursor                  #CACCCC
cursor_text_color       #101315
selection_foreground    #101315
selection_background    #798186
active_tab_background   #1A1E20
active_tab_foreground   #798186
inactive_tab_background #202528
inactive_tab_foreground #9FA5A9

background_opacity 0.90
